### ISSUE TITLE
Dataset upload behavior

### ISSUE THREAD

**Issue by geralddejong** [delving/culture-hub#110]
Currently, uploading a dataset to the hub results in the hub saving it as a file while uploading, and then parsing that file later.  Only when the file is fully parsed does the HTTP upload request actually respond.  If parsing fails it will only appear after an upload and no longer during upload.

Insertion of records into mongo seems to go at about 50,000 per minute or just less than 1000 per second, which means that the http response arrives (in the case of TresoarPica) nearly 12 minutes after the file upload is complete.

I believe that parsing should be happening during upload so that the upload progress bar honestly represents the process.

**Comment by kiivihal** [comment]
I agree. This seems to be the most logical behavior.

**Comment by geralddejong** [comment]
Uploading to frisian-stories just now, even though it's only storing what it receives first, still took a good long time.  This may be uplink bandwidth here at the office, but it's surprising, compared to the zippy upload locally.  If the upload already takes probably 15 minutes, no harm in parsing while you're uploading.

**Comment by manuelbernhardt** [comment]
Does the file actually get parsed _later_? Or does it start to be parsed during upload, but the parsing takes longer than the upload?

Play has the following behavior regarding uploads: if the stream being uploaded passes a certain treshold (I think 10MB) the contents of the upload are dumped to disk, so that the upload is non-blocking and does not clog the memory (at least that's my current understanding of the code, see `play.data.parsing.ApacheMultipartParser`).

Play is designed not to work with long requests like these that take nearly forever, since it has a limited thread pool (3 threads for all requests given a dual-core machine). Requests like these should be handled via a continuation - I did not implement this at the moment due to lack of time. But essentially this also means that for tracking the progress of an upload we should have an API method instead of relying on the file upload.

**Comment by geralddejong** [comment]
Indeed I have no proof that the parsing is happening later, but I have experienced very long waits between upload-complete and the associated HTTP response.

**Comment by geralddejong** [comment]
The approach involving a continuation sounds interesting, but does that mean that parsing/inserting can be done during the upload of data, in a streaming fashion?  I'm not sure i like the idea of uploading with one thread and checking progress with another using an API call.

What is the rationale for such severe rationing of threads in play?  Presumably the idea is that continuations should be responsible for simulating many-threading.  Still, seems like we could limit the number of simultaneous dataset uploads if necessary.

**Comment by manuelbernhardt** [comment]
So what happens is that the uploaded stream is consumed early but the response is blocked until the parsing is completed.

I think an appropriate solution for this would be to:
- close the HTTP connection as soon as the upload is done
- process the parsing in a separate thread (via a play job)
- offer an API that can be polled by the Sip-Creator to track progress and status (sucess, failure).

This would however mean we don't upload a stream anymore but a file (so that we can effectively close the request once the whole request has been received).

An alternative would be to use WebSockets, but the current support in play-scala is poor. There is much better support to be expected for Play 2.0 for this (featuring akka and friends) but that is not there yet.

All that being said - I would propose to tackle this issue after our deadline for FS, unless it really hinders work a lot. Or will clients directly upload things until then?

**Comment by geralddejong** [comment]
Perhaps an easy fix for the time being would be to end the HTTP request when the upload is finished and show how many records are currently inserted on the datasets page (perhaps that is already a live count).  The post-upload wait is something we have to fix, because from the sip-creator's perspective it is in limbo with no feedback for an extended period.

I don't understand why websockets would be necessary because that's for pushing to clients.  Here we are just pushing bytes to a server, and it could just as well be interpreting what it receives and acting on it rather than first receiving a file and only later chewing on it.  No need to send information back to the client since the client knows what it has sent so far, and therefore how complete the work is, as reflected in its progress bar.

**Comment by manuelbernhardt** [comment]
Ok, this is fixed now I believe. We release the connection once the upload is done and fire off an akka actor to take care of the parsing & inserting. During that time the DataSet is in the `processing` state
