### ISSUE TITLE
Adding objects to collections/stories user does not own

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#264]
related work flows which should be implemented:

Add Object to collection (user does not own object)
Add Object to story (user does not own object)
Delete Object from collection (user does not own obejct)
Delete Object from story (user does not own obejct)

This entails some thoughts on how on the creation page objects of others can be retrieved (search or user needs to bookmark this before ...)

**Comment by manuelbernhardt** [comment]
Yeah this is going to be a tricky one regarding the interface. @zemyatin the widget we have now for adding objects based on checkboxes doesn't quite fit to this. Probably the simplest for now is that once we have the "Bookmarks" collection, a user can fetch stuff from there. Later on we need a better interface for selecting objects - an embedded search of sorts.

**Comment by zemyatin** [comment]
Here's the lo'down.
1) Objects that a user does not own ie uploaded themselves, can only be added to a collection via the drag and drop functionality on the search results page
2)On the search results page the user can choose what collection to add these objects too. Then if the user wants to use these objects in a story they can do so.
3) Removing the non-owned objects from a collection is done in the user's collection edit page. There they can simply remove the object from the list of objects. This only removes the object from the collection, it does not delete the object
So that means no extra functionality on the collection edit page to add objects that a user does not own.
