### ISSUE TITLE
user profile pages produce 404

### ISSUE THREAD

**Issue by stillinsky** [delving/culture-hub#322]
http://frieseverhalen.delving.org:9001/stillinsky

**Comment by manuelbernhardt** [comment]
Yes, I noticed that one too - it happens when you're not logged in and a user has their profile marked as private. This one is tricky because you don't really want to query for each user's profile status when showing an item. We could store it redundantly but well... Another option would be to show a page but with minimal information, such as only the userName and a small text saying "this user does not have a profile" or so. Would that do the trick?

**Comment by stillinsky** [comment]
Yes, I think we can go for the last option. Just display the avatar and the user name. I think we do not even need to write anything about the profile.
