### ISSUE TITLE
Add extra description to the OAI-PMH listSets output 

### ISSUE THREAD

**Issue by kiivihal** [delving/culture-hub#597]
For harvesting datasets from our repository it would be nice if the description of the listSets output would be a bit more verbose with information we have stored in our DataSet object already.

Below you find a list of some suggestions I think are applicable. I think they should be outputted in name : value pairs so it is easy for other people to understand which is which.
- DataProvider name
- CollectionName
- nr of valid see records
- nr of digital objects
- nr of landing pages"

**Comment by manuelbernhardt** [comment]
We can use the `<setDescription>` for that purpose: http://www.openarchives.org/OAI/openarchivesprotocol.htm#ListSets

**Comment by kiivihal** [comment]
I think this is the right place for this extra information

## 

Sjoerd Siebinga
Delving B.V., Rotterdam
http://www.delving.eu (http://www.delving.eu/)
skype: sjoerdsiebinga
mobile: +31681926731

**Comment by manuelbernhardt** [comment]
What is "nr of valid see records"?

**Comment by manuelbernhardt** [comment]
Ok, I started working on this and it's actually not so simple, because the nr of digital objects and nr of landing pages are not part of any interoperability format we have, nor of the statistics that come from the sip-creator in any way.

They may be computed from SOLR but I refuse to introduce a dependency between the OAI-PMH service and SOLR. Those things are now decoupled and IMO this is a very good thing.

So I think this needs to be evaluated together with @geralddejong.

**Comment by geralddejong** [comment]
Landing page is one of our SystemField entries.

**Comment by kiivihal** [comment]
I think I meant ESE record. 'see was a typo.

## 

Sjoerd Siebinga
Delving B.V., Rotterdam
http://www.delving.eu (http://www.delving.eu/)
skype: sjoerdsiebinga
mobile: +31681926731

**Comment by manuelbernhardt** [comment]
I'll close this issue at the moment, as we don't have a good interoperability format for getting those statistics back. 

Once we have a statistics repository of sorts, we'll get back to this.
