### ISSUE TITLE
Virtual collections label > "Virtual OAI Collection"

### ISSUE THREAD

**Issue by zemyatin** [delving/culture-hub#675]

**Comment by manuelbernhardt** [comment]
Uhm, is this a renaming proposal?

I think we should discuss this because the agreed upon name after our discussion in July which isn't yet reflected in the interface is Custom Harvest Collection. So instead of introducing yet another name for the same thing I'd rather prefer to rename everything to Custom Harvest Collection.

**Comment by zemyatin** [comment]
No, this is not a renaming proposal.. this is just a message label. "Virtual Collection" as it is now implies that it may be "searchable" via the api or hub itself. This is for the user, and it can still be "Custom Harvest Collection" ... just want to make that clearer to the user. It can still be "Custom Harvest Collection", as long as the distinction is made more clear for the user
