### ISSUE TITLE
move footer content from conf to cms (ala homepage)

### ISSUE THREAD

**Issue by zemyatin** [delving/culture-hub#730]

**Comment by manuelbernhardt** [comment]
I'd actually argue that this should stay in the configuration, because

1) the footer is not likely to change that often
2) querying the footer from the db for each page load adds unnecessary strain

If we go the route of having things be changeable via the interface for convenience there's a lot more high priority items on the list, such as the indexing configuration etc. - we are going to have a "live" configuration at some point anyhow, so let's tackle it then.
