### ISSUE TITLE
Dataset page sort freezes whole page

### ISSUE THREAD

**Issue by kiivihal** [delving/culture-hub#866]
When you select any sort - but in particular the sort on the nr of records - the whole page freezes and becomes unresponsive and it can take in excess of 20 sec for other clicks to be executed. It is even impossible to refresh the page.

I have tested this on chrome and safari (mac os x 10.8)

**Comment by manuelbernhardt** [comment]
The issue here is that the column that contains the number of records is in no way simple. It contains:
- the number of records
- the list of schemas and valid records (shown when hovering over it)
- when a set is being indexed, a counter with what is being processed

This is too much to take for the jQuery plugin that does the table sorting.

What I'll do is to try and disable sorting on this column for the moment, and see if there is a way to sort this column (likely with another library) as part of 12.04

**Comment by kiivihal** [comment]
Ok. That sounds fine to me.

On Fri, Apr 5, 2013 at 10:16 AM, Manuel Bernhardt
notifications@github.comwrote:

> The issue here is that the column that contains the number of records is
> in no way simple. It contains:
> - the number of records
> - the list of schemas and valid records (shown when hovering over it)
> - when a set is being indexed, a counter with what is being processed
> 
> This is too much to take for the jQuery plugin that does the table sorting.
> 
> What I'll do is to try and disable sorting on this column for the moment,
> and see if there is a way to sort this column (likely with another library)
> as part of 12.04
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/delving/culture-hub/issues/866#issuecomment-15943724
> .

## 

Sjoerd Siebinga
Delving B.V., Rotterdam
http://www.delving.eu
skype: sjoerdsiebinga
mobile: +31681926731
